@startuml ghostfire

start

if (callback type) then (no)
  #Orange:timer;
  #Orange:endRound();
  else (yes)
  #Orange:button;
  if (ghost button) then (yes)
 #Orange:resetGhost(id);
  else (no)
  #Orange:newGame();
  endif
endif
stop


start
if (newGame()) then (yes)
  :set ghosts alive;
  :re-set gameRound;
  :set gameRunning true;
  :set gameScore 0;
  :new game pixles;
  #Orange:newRound();

elseif (newRound()) then (yes)
  :set gameRound +1;
  :set poltergeist ghost;
  :set orb ghosts;
  :pixels on;
  #Green:ROUND_TIMER;

elseif (endRound()) then (yes)
  #Red:ROUND_TIMER;
  :Ghosts pixles off;
  if (last round) then (yes)
    #Orange:endGame();
  else (no)
    #Orange:newRound();
  endif

elseif (ghostShot(id)) then (yes)
    if (game inprogress) then (yes)
      if (Was poltergeist) then (yes)
        :set poltergeist ghost;
        :set gameScore ++;
      endif
    #Orange:endRound();
    else (no)
      #Orange:ghostReset(id);
    endif

elseif (ghostReset(id)) then (yes)
    :set orb ghosts;
    :pixel readyon;

elseif (endRound()) then (yes)
  #Red:ROUND_TIMER;
  if (last round) then (yes)
    #Orange:endGame();
  else (no)
    #Orange:newRound();
  endif
  :Ghosts pixles off;

elseif (endGame()) then (yes)
  #Red:ROUND_TIMER;
  :set gameRunning false;
  :End Game colour;

elseif (finalScore()) then (yes)
  if (winning score) then (yes)
    :winning pixles;
  else (no)
    :no pixles;
  endif

endif
stop
@enduml